### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by nyle1995** [alipay/jarslink#86]
现在实际上调用方，看不到模块提供者的api 定义的
而且使用起来有点不方便

建议是封装一层， 提供 Builder 代理类的方法。
代理类的工作 ： 把class，method，参数等信息传到模块中去执行。

A 服务引用 模块B提供的api jar包，然后 生成代理类，在A服务中直接api调用

**Comment by kiral** [comment]
模块提供者的api 需要做一个单独的SDK。
