### ISSUE TITLE
有2.0的example吗

### ISSUE THREAD

**Issue by wengwh** [alipay/jarslink#88]
有2.0的example吗

**Comment by QilongZhang** [comment]
@wengwh  在 README [快速开始](https://github.com/alipay/jarslink#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B) 中有四个demo 和文档。

**Comment by wengwh** [comment]
@QilongZhang  有个需求，rpc调用使用了dubbo，网关模块当做dubbo消费者，不想用dubbo泛化调用。想通过jarslink 来引入提供者的 api 包，动态链接起来。可以实现吗？

**Comment by QilongZhang** [comment]
@wengwh  大致理解你的意思，是打算dubbo服务提供方和消费方部署在一起，走内部调用，不再走网络调用？

**Comment by wengwh** [comment]
@QilongZhang  我们原来网关调用dubbo服务提供http接口，这样每次开发新的dubbo服务，就要修改网关，我想提取出来，独立一个dubbo调用包，里面调用dubbo服务，同时提供http服务，通过jarslink嵌入网关。

**Comment by QilongZhang** [comment]
@wengwh 可以做的，你需要熟悉了解 [Jarslink2.0] (http://www.sofastack.tech/sofa-boot/docs/sofa-jarslink-jarslink-readme) 文档和Demo演示，代码改造理论上会很小。建议尝试，改造过程中遇到问题，可以邮件我。

**Comment by wengwh** [comment]
@QilongZhang  谢谢
